pipeline {
  agent any
  tools {
    nodejs 'Node11.0.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        bat 'cd jenkinsTest && npm i'
      }
    }
    stage('Run tests') {
      steps {
        bat 'cd jenkinsTest && npm t'
      }
    }
    stage("RUN REMOTE"){
        steps{
            build job: 'parameterized', parameters: [string(name:'ROO_ID',value:'$BUILD_ID')], wait: false
        }
    }
  }
}
